# this just for fun
# Vastunna sudha vastunana sudha
# kitne aadmi the!
# Basanti!! inn kutho ki samne mat nachna...
# Jai BajrangBali
# Namo Parvati pathe.... Har Har Mahadev...
# Jai Shree Ram
# Sree Ram.
# Ram Lakshman Janaki jai bolo Hanuman ki...
# Om Namah Shivaya!...
